timezone: Asia/Bangkok

commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'

paths:
  static: static
  uploads: static/img

markdown:
  engine: commonmark
  options: {}

collections_config:
  pages:
    path: src/pages
    url: "/[full_slug]/"
    name: Pages
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: text_ad
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    _inputs:
      title:
        type: text
        comment: The page title.
  blog:
    path: blog
    url: "/blog/{slug}/"
    name: Blog
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: event_available
    disable_add_folder: true
    schemas:
      default:
        name: Blog Post
        path: .cloudcannon/schemas/blog.mdx
        create: 
          path: '{date|year}-{date|month}-{date|day}-{slug|slugify}.mdx'
          _inputs:
            date:
              type: date
              instance_value: NOW
              comment: Used to order the blog posts.
    _inputs:
      title:
        type: text
        comment: The blog post title.
      authors:
        type: multiselect
        options:
          values: data.authors
          value_key: id
          preview:
            text:
              - key: name
      tags:
        type: multiselect
        options:
          values: data.tag
          value_key: label
  docs:
    path: docs
    url: "/docs/[full_slug]/"
    name: Docs
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: docs
    schemas:
      default:
        path: .cloudcannon/schemas/doc.mdx
    _inputs:
      title:
        type: text
        comment: The text title of your document. Used for the page metadata and as a fallback value in multiple places (sidebar, next/previous buttons...). Automatically added at the top of your doc if it does not contain any Markdown title.
  data:
    path: data
    disable_url: true
    disable_add_folder: true
    icon: settings

data_config:
  authors:
    path: data/blog-authors.yml
  tags:
    path: data/blog-tags.yml

file_config:
  - glob: data/blog-authors.yml
    _inputs:
      $:
        type: array
        label: Blog Authors
        options:
          structures: _structures.author
  - glob: data/blog-tags.yml
    _inputs:
      $:
        type: array
        label: Blog Tags
        options:
          structures: _structures.tag
  - glob: data/docs-sidebar.json
    _inputs:
      $:
        type: array
        label: Sidebar Configuration
        options:
          structures: _structures.sidebar_items
  - glob: data/site-config.json
    _inputs:
      favicon:
        type: image
      editUrl:
        type: url
        comment: Add your site's repo.
      blog:
        type: object
        options:
          preview:
            icon: newspaper
      showReadingTime:
        type: switch
        comment: Show reading time for blog articles.
      feedOptions:
        type: object
        options:
          preview:
            icon: newspaper
      feedOptions.type:
        type: multiselect
        comment: Type of feed to be generated.
        options:
          values: 
            - rss
            - atom
      feedOptions.xlst:
        type: switch
        comment: Permits to style the blog XML feeds with XSLT so that browsers render them nicely.
      navbar:
        type: object
        options:
          preview:
            icon: page_header
      navbar.logo:
        type: object
        options:
          preview:
            icon: image
      navbar.items:
        type: array
        options:
          structures: _structures.navbar_item
      footer:
        type: object
        options:
          preview:
            icon: page_footer
      footer.style:
        type: select
        options:
          values: 
            - primary
            - dark
      footer.links:
        type: array
        options:
          structures: _structures.footer_link_section

_inputs:
  slug:
    type: text
    comment: The page slug used for the url.
  draft:
    type: switch
    comment: Draft pages will only be available during development.
  unlisted:
    type: switch
    comment: Unlisted pages will be available in both development and production. They will be "hidden" in production, not indexed, excluded from sitemaps, and can only be accessed by users having a direct link.
  src:
    type: image
  alt:
    type: textarea

_structures:
  footer_link_section:
    values:
      - value:
          title:
          items:
        icon: list
        _inputs:
          items:
            options:
              structures: _structures.footer_link_item
  footer_link_item:
    values:
      - label: Internal link
        icon: link
        value:
          label:
          to:
        _inputs:
          to:
            type: url
            comment: Link to a page on the site.
            options:
              required: true
              disable_upload_file: true
              disable_direct_input: false
              disable_upload_file_in_file_browser: true
              hide_link_to_file: false
              hide_link_to_page: false
              hide_link_to_email_address: false
              hide_link_to_telephone: false   
      - label: External link
        icon: link
        value:
          label:
          href:
        _inputs:
          href:
            type: url
            comment: A full-page navigation, used for navigating outside of the website.
            options:
              required: true
              disable_upload_file: true
              disable_direct_input: false
              disable_upload_file_in_file_browser: true
              hide_link_to_file: false
              hide_link_to_page: true
              hide_link_to_email_address: false
              hide_link_to_telephone: false
  navbar_item:
    values:
      - label: Docs link
        icon: link
        value:
          type: docSidebar
          sidebarId: tutorialSidebar
          position:
          label:
        _inputs:
          type:
            hidden: true
          sidebarId:
            hidden: true
            comment: The ID of the sidebar that this item is linked to.
          position:
            type: select
            comment: The side of the navbar this item should appear on.
            options:
              values: 
                - left
                - right
      - label: Internal link
        icon: link
        value:
          to:
          position:
          label:
        _inputs:
          to:
            type: url
            comment: Link to a page on the site.
            options:
              required: true
              disable_upload_file: true
              disable_direct_input: false
              disable_upload_file_in_file_browser: true
              hide_link_to_file: false
              hide_link_to_page: false
              hide_link_to_email_address: false
              hide_link_to_telephone: false
          position:
            type: select
            comment: The side of the navbar this item should appear on.
            options:
              values: 
                - left
                - right
      - label: External link
        icon: link
        value:
          href:
          position:
          label:
        _inputs:
          href:
            type: url
            comment: A full-page navigation, used for navigating outside of the website.
            options:
              required: true
              disable_upload_file: true
              disable_direct_input: false
              disable_upload_file_in_file_browser: true
              hide_link_to_file: false
              hide_link_to_page: true
              hide_link_to_email_address: false
              hide_link_to_telephone: false
          position:
            type: select
            comment: The side of the navbar this item should appear on.
            options:
              values: 
                - left
                - right
  sidebar_items:
    values:
      - label: Link
        icon: link
        value:
          type: link
          href: 
          label:
        _inputs:
          type:
            hidden: true
          href:
            type: url
            options:
              required: true
              disable_upload_file: true
              disable_upload_file_in_file_browser: true
              hide_link_to_file: true
              hide_link_to_page: false
              hide_link_to_email_address: false
              hide_link_to_telephone: false
          label: 
            type: text
            comment: The text label for the page.
      - label: Docs Page
        icon: pages
        value:
          type: doc
          id: 
          label:
        _inputs:
          type:
            hidden: true
          id: 
            type: select
            comment: The page to use for the sidebar item.
            options:
              values: collections.docs
          label: 
            type: text
            comment: The text label for the page.
        preview:
          text:
            - key: label
          subtext:
            - key: id
      - label: Sidebar Category
        icon: category
        value:
          label:
          type: category
          collapsible: true
          collapsed: true
          link: 
          items: []
        _inputs:
          collapsed:
            type: switch 
          collapsible:
            type: switch
          link:
            type: object
            comment: Used to determine which page to link to when the category label is selected. Can be a generated index page, or an existing docs page.
            options:
              structures: _structures.sidebar_category_link
              empty_type: "null"
          type:
            hidden: true
          label: 
            type: text
            comment: The text label for the page.
          items:
            type: array
            options:
              structures: _structures.sidebar_items
        preview:
          text:
            - key: label
          subtext: Category
  sidebar_category_link:
    values:
      - label: Existing Docs Page
        icon: link
        value:
          type: doc 
          id: 
        _inputs:
          type:
            hidden: true
          id:
            type: select
            options:
              values: collections.docs
      - label: Generated Index Page
        icon: grid_view
        value:
          type: generated-index
          title:
          slug:
          description: 
          keywords: []
          image: 
        _inputs:
          type:
            hidden: true
          title:
            type: text
            comment: The title for the category index page.
          slug:
            type: text
            comment: Allows you to customize the generated page's route, which defaults to /category/[categoryName].
          description:
            type: textarea
            comment: An optional description for the category index page.
          keywords:
            type: array
            comment: Used for keywords in the page's metadata, which are used for SEO purposes.
          keywords[*]:
            type: text
          image:
            type: image
            comment: Used for metadata image.
  tag:
    values:
      - value:
          label:
          permalink:
          description:
        preview:
          icon: tag
          text:
            - key: label
          subtext:
            - key: description
        _inputs:
          permalink:
            type: url
            options:
              required: true
              disable_upload_file: true
              disable_direct_input: true
              disable_upload_file_in_file_browser: true
              hide_link_to_file: true
              hide_link_to_page: false  
              hide_link_to_email_address: true
              hide_link_to_telephone: true
  author:
    values:
      - value:
          id: 
          name: 
          title: 
          url: 
          image_url: 
          page: true
          socials:
            x: 
            linkedin: 
            github: 
            newsletter:
        _inputs:
          id:
            type: text
            comment: A unique author id.
          title:
            type: text
            comment: The job title of the author.
          page:
            type: switch
            comment: If set to true a page will be automatically generated for this author on this site.
          socials:
            type: object
            options:
              preview:
                icon: communities
        preview:
          icon: article_person
          text:
            - key: name
          subtext:
            - key: title
          image:
            - key: image_url

_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4 h5 h6
    italic: true
    link: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    numberedlist: true
    indent: true
    outdent: true
    join_above: true
    join_below: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    snippet: true

_snippets_imports:
  mdx: true
  docusaurus_mdx: true  

_snippets:
  button:
    template: mdx_paired_component
    inline: true
    preview:
      text: Alert Button
    definitions:
      component_name: AlertButton
      content_key: inner_text
      named_args:
        - editor_key: alert_text
          type: string
        - editor_key: color
          type: string
  highlight:
    template: mdx_paired_component
    inline: true
    preview:
      text: Highlighted Text
    definitions:
      component_name: Highlight
      content_key: inner_text
      named_args:
        - editor_key: color
          type: string