timezone: Asia/Bangkok

paths:
  static: static
  uploads: static/img

markdown:
  engine: commonmark
  options: {}

collections_config:
  pages:
    path: src/pages
    url: "/[full_slug]/"
    name: Pages
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: text_ad
  blog:
    path: blog
    url: "/blog/{slug}/"
    name: Blog
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: event_available
    schemas:
      default:
        path: .cloudcannon/schemas/blog.md
    _inputs:
      authors:
        type: multiselect
        options:
          values: data.authors
          value_key: id
          preview:
            text:
              - key: name
      tags:
        type: multiselect
        options:
          values: data.tags
          value_key: id
  docs:
    path: docs
    url: "/docs/[full_slug]/"
    name: Docs
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: docs
    schemas:
      default:
        path: .cloudcannon/schemas/doc.md
  data:
    path: data
    disable_url: true
    disable_add_folder: true
    icon: settings

data_config:
  authors:
    path: data/authors.yml
  tags:
    path: data/tags.yml

_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4 h5 h6
    italic: true
    link: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    numberedlist: true
    indent: true
    outdent: true
    join_above: true
    join_below: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    snippet: true

_snippets_imports:
  mdx: true
  docusaurus_mdx: true  