timezone: Asia/Bangkok

paths:
  static: static
  uploads: static/img

markdown:
  engine: commonmark
  options: {}

collections_config:
  pages:
    path: src/pages
    url: "/[full_slug]/"
    name: Pages
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: text_ad
  blog:
    path: blog
    url: "/blog/[full_slug]/"
    name: Blog
    glob: 
      - "**/*.md"
    icon: event_available
  blog_data:
    path: blog
    disable_url: true 
    name: Blog Data
    glob: 
      - "*.yml"
    icon: settings
  docs:
    path: docs
    url: "/docs/[full_slug]/"
    disable_add_folder: true
    name: Docs
    glob: 
      - "**/*.md"
      - "**/*.mdx"
      - "**/_category_.json"
    icon: docs
    schemas:
      default:
        path: .cloudcannon/schemas/docs.md
        create: 
          path: "[relative_base_path]/{filename|slugify}.md"
      docs_section_data:
        path: .cloudcannon/schemas/_category_.json
        create: 
          path: "{section_name|slugify}/_category_.json"