timezone: Asia/Bangkok

paths:
  static: static
  uploads: static/img

markdown:
  engine: commonmark
  options: {}

collections_config:
  pages:
    path: src/pages
    url: "/[full_slug]/"
    name: Pages
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: text_ad
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    _inputs:
      title:
        type: text
        comment: The page title.
  blog:
    path: blog
    url: "/blog/{slug}/"
    name: Blog
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: event_available
    schemas:
      default:
        path: .cloudcannon/schemas/blog.mdx
    _inputs:
      title:
        type: text
        comment: The blog post title.
      authors:
        type: multiselect
        options:
          values: data.authors
          value_key: id
          preview:
            text:
              - key: name
      tags:
        type: multiselect
        options:
          values: data.tags
          value_key: id
  docs:
    path: docs
    url: "/docs/[full_slug]/"
    name: Docs
    glob: 
      - "**/*.md"
      - "**/*.mdx"
    icon: docs
    schemas:
      default:
        path: .cloudcannon/schemas/doc.mdx
    _inputs:
      title:
        type: text
        comment: The text title of your document. Used for the page metadata and as a fallback value in multiple places (sidebar, next/previous buttons...). Automatically added at the top of your doc if it does not contain any Markdown title.
  data:
    path: data
    disable_url: true
    disable_add_folder: true
    icon: settings

data_config:
  authors:
    path: data/authors.yml
  tags:
    path: data/tags.yml

file_config:
  - glob: data/authors.yml
    _inputs:
      $:
        type: array
        label: Blog Authors
        options:
          structures: _structures.author

_inputs:
  slug:
    type: text
    comment: The page slug used for the url.
  draft:
    type: switch
    comment: Draft pages will only be available during development.
  unlisted:
    type: switch
    comment: Unlisted pages will be available in both development and production. They will be "hidden" in production, not indexed, excluded from sitemaps, and can only be accessed by users having a direct link.

_structures:
  author:
    values:
      - value:
          id: 
          name: 
          title: 
          url: 
          image_url: 
          page: true
          socials:
            x: 
            linkedin: 
            github: 
            newsletter:
        _inputs:
          id:
            type: text
            comment: A unique author id.
          title:
            type: text
            comment: The job title of the author.
          page:
            type: switch
            comment: If set to true a page will be automatically generated for this author on this site.
        preview:
          icon: article_person
          text:
            - key: name
          subtext:
            - key: title
          image:
            - key: image_url

_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4 h5 h6
    italic: true
    link: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    numberedlist: true
    indent: true
    outdent: true
    join_above: true
    join_below: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    snippet: true

_snippets_imports:
  mdx: true
  docusaurus_mdx: true  

_snippets:
  button:
    template: mdx_paired_component
    inline: true
    preview:
      text: Alert Button
    definitions:
      component_name: AlertButton
      content_key: inner_text
      named_args:
        - editor_key: alert_text
          type: string
        - editor_key: color
          type: string
  highlight:
    template: mdx_paired_component
    inline: true
    preview:
      text: Highlighted Text
    definitions:
      component_name: Highlight
      content_key: inner_text
      named_args:
        - editor_key: color
          type: string